---
output: html_document
pagetitle: "Homework 2, Group 9: to the Client"
---

 ```{css, echo=FALSE}
     .disclosure{
     text-align: justify;
     margin-left: auto;
     margin-right: auto;
     font-style: italic;
     width: 80%;
     }

```

## Dear valued Client,
### Please find below our finalized report with your current options. Please contact us if you need anything else, we will be happy to assist you in this new journey!.
\

#### Best regards,
##### Ana Gabriela Itokazu, Jianfeng Zhang, and Takhellambam Bijoychandra Singh.

***
<div class="disclosure">

Portfolio developed for a homework activity during the class STAT 6210 - R Programming for Data Science (Auburn University, Fall 2020). The general idea is that the group works as a quantitative analysts for an investment bank, and we needed to present a Portfolio for our boss (Dr. Molinari, in this very real case) with a client's options. This document was produced in RMarkDown, and finalized in `r format(Sys.Date(), '%B %d, %Y')`. One can find more about this assignment [here](https://github.com/AU-R-Programming/HW2-9/blob/master/ToTheClient.Rmd).

</div>

***
<div style="text-align: justify">

# Financial Report

#### Required output: Produce a short html file (not more than the equivalent of two pages) representing a brief financial report for the client (no code details) describing what was done and what your conclusions are.

Suppose that you are working in an investment bank as a quantitative analyst. Your boss asks you to create a portfolio for one of your clients. The client wants to find the portfolio with the smallest variance that satisfies the following constraints:

- Considers only 5 companies of the S&P500.
- The investment C is exactly $1,000,000.
- You are allowed to invest in a maximum of 3 stocks.

If needed, it is possible to consider weights with negative values. This means that you are allowed to short stocks.

Your boss wants you to compute all possible portfolios that satisfy the client’s constraints, for each portfolio size (i.e. 1, 2 and 3 stocks) create a matrix with understandable row and column names in which, for each portfolio, you will store weights (when considering more than one stock in a portfolio),
expected returns and risk, represent them graphically as (for example) in the graph below, and provide the weights of the best (i.e. minimum variance) portfolio with expected return and risk (i.e. variance).
For the last task, in order to find the optimal weights we denote the vector of weights as \(\mathbf{w} \in \mathbb{R}^p\), where \(p\) is the number of stocks to invest, and denote the variance-covariance matrix of stocks as \(\mathbf{\Sigma}\). Then given the constraint that \(\mathbf{w}^T \mathbf{1} = 1\), where \(\mathbf{1}\) is the vector of \(1\) of length \(p\), we can construct the objective function with Lagrange multiplier as \(f(\mathbf{w}) = \mathbf{w}^T \mathbf{\Sigma} \mathbf{w} + \lambda(\mathbf{w}^T \mathbf{1} - 1)\) with some \(\lambda\). The optimal weights are therefore given by \[
\mathbf{w}^* = \frac{\mathbf{\Sigma}^{-1} \mathbf{1}}{\mathbf{1}^T \mathbf{\Sigma}^{-1} \mathbf{1}}.
\] Based on these weights, the expected return and risk are respectively given by \[\mu^* = ({\mathbf{w}^*}^T \mathbf{\mu}) \,C\] and \[\sigma^* = ({\mathbf{w}^*}^T \mathbf{\Sigma} \mathbf{w}^*) \, C^2\] where \(\mathbf{\mu}\) is the vector of expected (average) returns and \(C\) is the total investment.









</div>

```{r stock, echo=FALSE}
library(rvest)
library(quantmod)
url <- "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
SP500 <- url %>%
     xml2::read_html() %>%
     html_nodes(xpath='//*[@id="mw-content-text"]/div/table[1]') %>%
     html_table()
SP500 <- SP500[[1]]
Tix <- SP500$Symbol

#randomly select 5 stocks
set.seed(10)
stocks_tickers=sample(Tix, 5)
stocks_tickers

#time span for last 3 years
three_year_ago <- seq(as.Date("2020-04-01"), length = 2, by = "-3 year")[2]
getSymbols(stocks_tickers, from = three_year_ago, to = as.Date("2020-04-01"))


stock1<- na.omit(ClCl(get(stocks_tickers[1])))
stock2 <- na.omit(ClCl(get(stocks_tickers[2])))
stock3<- na.omit(ClCl(get(stocks_tickers[3])))
stock4 <- na.omit(ClCl(get(stocks_tickers[4])))
stock5<- na.omit(ClCl(get(stocks_tickers[5])))

sigma_stocks <- var(cbind(stock1, stock2,stock3,stock4,stock5))
sigma_stocks
```

